theme: jekyll-theme-cayman
title: "Predicting links in a Knowledge Graph: from raw data to insights"
description: "KGC 2023 Master class, Monday May 8th 2023 9:00 AM EDT"
markdown: kramdown
markdown_ext: md
url: "https://raw2links-kgc23.github.io"
plugins:
  - jemoji
